# MkDocs configuration for CircONTrack documentation
site_name: CircONTrack
site_description:  Circular DNA Tracking and Detection via ONT-based Multi-modal Signal Integration
site_author: Samarth Mathur
site_url: https://samarth8392.github.io/CircONTrack/
repo_name: CircONTrack
repo_url: https://github.com/samarth8392/CircONTrack

# Theme configuration
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - bash
    - yaml
  navigation_depth: 2
  titles_only: false

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
  - User Guide:
    - Overview: pipeline_overview.md
    - Pipeline: pipeline_flowchart.md
    - Classify: classify_usage.md
  - Algorithm:
    - Workflow: workflow.md
    - Classify: classify.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JS
extra_css:
  - css/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.4.0/dist/mermaid.min.js
  - js/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: date

# Extra information
extra:
  social:
    - icon: fontawesome/solid/users
      link: https://samarth8392.github.io
    - icon: fontawesome/brands/github
      link: https://github.com/samarth8392