# MkDocs configuration for circDNA_detection documentation
site_name: circDNA Detection
site_description: ONT-optimized circular DNA detection via multi-modal analysis
site_author: Samarth Mathur
site_url: https://samarth8392.github.io/circDNA_detection/
repo_name: samarth8392/circDNA_detection
repo_url: https://github.com/samarth8392/circDNA_detection
edit_uri: edit/main/docs/

# Theme configuration
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - bash
    - yaml
  navigation_depth: 3
  titles_only: false
  
# Alternative modern theme (comment out readthedocs above and uncomment below)
# theme:
#   name: material
#   palette:
#     - scheme: default
#       primary: blue
#       accent: blue
#       toggle:
#         icon: material/brightness-7
#         name: Switch to dark mode
#     - scheme: slate
#       primary: blue
#       accent: blue
#       toggle:
#         icon: material/brightness-4
#         name: Switch to light mode
#   features:
#     - navigation.tabs
#     - navigation.sections
#     - navigation.top
#     - search.highlight
#     - content.code.annotate

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
  - User Guide:
    - Overview: pipeline_overview.md
    - Pipeline: pipeline_flowchart.md
  - Algorithm:
    - Workflow: workflow.md
    

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JS
extra_css:
  - css/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.13.8/mermaid.min.js
  - js/extra.js

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: date

# Extra information
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/samarth8392
  version:
    provider: mike