name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libz-dev libbz2-dev liblzma-dev
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pysam>=0.19.0 numpy>=1.19.0 scipy>=1.6.0
        pip install -e .
    
    - name: Test CLI works
      run: |
        circDNA-detect --help
    
    - name: Test Python import
      run: |
        python -c "from circDNA_detection import CircularDNADetector; print('Package works!')"
    
    - name: Run tests (if they exist)
      run: |
        if [ -d "tests" ]; then
          pip install pytest
          pytest tests/
        else
          echo "No tests directory found, skipping tests"
        fi